-- rails generate scenic:model rental_listing_with_asset
SELECT 
  -- TODO - add uuid..
  rental_listings.project_uuid,
  rental_listings.discarded_at,
  rental_listings.id,
  rental_listings.reference,
  rental_listings.flags,
  rental_listings.furnished,
  rental_listings.reserved,
  rental_listings.highlighted,
  rental_listings.archived,
  rental_listings.visible,
  rental_listings.hide_map,
  rental_listings.obscure_map,
  rental_listings.main_video_url,
  rental_listings.details,
  rental_listings.related_urls,
  rental_listings.publish_from,
  rental_listings.publish_till,
  rental_listings.realty_asset_id,
  rental_listings.translations,
  -- rental_listings.price_sale_current_cents,
  -- rental_listings.price_sale_current_currency,
  -- rental_listings.price_sale_original_cents,
  -- rental_listings.price_sale_original_currency,
  rental_listings.commission_cents,
  rental_listings.commission_currency,
  rental_listings.service_charge_yearly_cents,
  rental_listings.service_charge_yearly_currency,
  rental_listings.price_rental_monthly_low_season_cents,
  rental_listings.price_rental_monthly_low_season_currency,
  rental_listings.price_rental_daily_low_season_cents,
  rental_listings.price_rental_daily_low_season_currency,
  rental_listings.price_rental_monthly_high_season_cents,
  rental_listings.price_rental_monthly_high_season_currency,
  rental_listings.price_rental_daily_high_season_cents,
  rental_listings.price_rental_daily_high_season_currency,
  rental_listings.price_rental_monthly_standard_season_cents,
  rental_listings.price_rental_monthly_standard_season_currency,
  rental_listings.price_rental_daily_standard_season_cents,
  rental_listings.price_rental_daily_standard_season_currency,
  rental_listings.currency,
  rental_listings.import_url,
  rental_listings.created_at,
  rental_listings.updated_at,
  realty_assets.reference AS asset_reference,
  realty_assets.longitude,
  realty_assets.latitude,
  realty_assets.year_construction,
  realty_assets.count_bathrooms,
  realty_assets.count_bedrooms,
  realty_assets.count_toilets,
  realty_assets.count_garages,
  realty_assets.plot_area,
  realty_assets.constructed_area,
  realty_assets.area_unit,
  realty_assets.energy_rating,
  realty_assets.energy_performance,
  realty_assets.street_number,
  realty_assets.street_name,
  realty_assets.street_address,
  realty_assets.postal_code,
  realty_assets.province,
  realty_assets.city,
  realty_assets.city_search_key,
  realty_assets.region,
  realty_assets.country,
  realty_assets.floor,
  realty_assets.neighborhood,
  realty_assets.neighborhood_search_key,
  realty_assets.google_place_id
  -- pages.translations AS shared_page_translations
 FROM rental_listings,
  realty_assets
-- LEFT JOIN pages 
--   ON pages.slug = 'rental_listing_shared_page'
WHERE (rental_listings.realty_asset_id = realty_assets.id);
-- results = ActiveRecord::Base.connection.exec_query("select * from rental_listings, realty_assets where realty_asset_id = realty_assets.id")